version: '3.8'

services:
  # 1. Database MongoDB
  mongo_db:
    image: mongo:latest
    restart: always
    container_name: utc_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - utc_network
    # --- LIMITASI RESOURCE ---
    deploy:
      resources:
        limits:
          cpus: '0.50'        # Maksimal pakai 50% dari 1 Core CPU
          memory: 512M        # Maksimal RAM fisik 512MB (Selebihnya masuk Swap)
        reservations:
          memory: 128M        # Garansi RAM minimal 128MB agar stabil

  # 2. Backend (Server API)
  backend:
    build: ./backend
    container_name: utc_backend
    restart: always
    ports:
      - "5200:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo_db:27017/bengkel_utc
      - JWT_SECRET=rahasia_super_aman_docker
      - NODE_ENV=development
    depends_on:
      - mongo_db
    networks:
      - utc_network
    # --- LIMITASI RESOURCE ---
    deploy:
      resources:
        limits:
          cpus: '0.50'        # Maksimal pakai 50% dari 1 Core CPU
          memory: 300M        # Node.js backend cukup ringan, 300MB cukup
        reservations:
          memory: 100M        # Garansi RAM minimal

  # 3. Frontend (Web Interface)
  frontend:
    build: ./frontend
    container_name: utc_frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - utc_network
    # --- LIMITASI RESOURCE ---
    deploy:
      resources:
        limits:
          cpus: '0.25'        # Frontend statis (Nginx) sangat ringan, 25% CPU cukup
          memory: 128M        # 128MB sangat cukup untuk serve file statis
        reservations:
          memory: 32M

networks:
  utc_network:
    driver: bridge

volumes:
  mongo_data: {}